- .github/workflows/bandit.yaml
> Bandit security scanner

- .github/workflows/black.yaml
- pyproject.toml
> Black linter on CI

- src/app/endpoints/models.py
- src/app/routers.py
> Endpoint with model list

- src/app/endpoints/root.py
- src/app/routers.py
> Root endpoint handler

- lightspeed-stack.yaml
- src/lightspeed-stack.py
> Configuration loader

- pdm.lock
- pyproject.toml
> New dependency: llama-stack

- src/app/endpoints/config.py
- src/app/routers.py
> Config endpoint

- src/configuration.py
- src/lightspeed-stack.py
> Configuration loading code

- pdm.lock
- pyproject.toml
Add Rich library as dependency
> Add Rich library as dependency

- src/configuration.py
- src/lightspeed-stack.py
- src/runners/uvicorn.py
> Proper logging in the service

- src/app/main.py
- src/configuration.py
> Minor fixes

- src/app/main.py
- src/lightspeed-stack.py
- src/log.py
- src/runners/uvicorn.py
> Logging improvement

- .gitignore
Ignore JetBrains' IDE folders
Ignoring the whole folder is a lot more simple than the [recommended](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore) piece-meal exclusion.
- Closes #
> Ignore JetBrains IDE folders.

- Makefile
- src/app/endpoints/models.py
- src/app/endpoints/query.py
- src/app/main.py
- src/client.py
- src/configuration.py
- src/log.py
- tests/integration/test_configuration.py
- tests/unit/app/test_routers.py
- tests/unit/models/test_config.py
- tests/unit/test_client.py
- tests/unit/test_configuration.py
- tests/unit/test_log.py
LCORE-159: fix type bugs
- Related Issue #LCORE-159
> LCORE-159: fix type bugs

- .github/workflows/mypy.yaml
GitHub action to run Mypy on CI
- Related Issue #LCORE-159
> LCORE-159: GitHub action to run Mypy on CI

- src/lightspeed-stack.py
LCORE-158: selectable configuration dump
> LCORE-158: selectable configuration dump

- tests/unit/runners/test_uvicorn_runner.py
> Unit test for Uvicorn runner

- tests/unit/app/endpoints/test_config.py
Unit tests for `/config` endpoint
> Unit tests for /config endpoint

- pdm.lock
- pyproject.toml
To upgrade llama_stack version to 0.2.9
- Related Issue # NA
- Closes # https://issues.redhat.com/browse/AAP-47015
> To upgrade llama_stack version to 0.2.9

- src/configuration.py
- tests/unit/test_configuration.py
> Config for uvicorn

- src/lightspeed_stack.py
- src/runners/uvicorn.py
- tests/unit/runners/test_uvicorn_runner.py
> Configuration for runner

- tests/unit/app/endpoints/__init__.py
- tests/unit/runners/__init__.py
> Initfiles in unit tests

- pdm.lock
- pyproject.toml
> Bump-up Uvicorn to 0.43.3

- tests/unit/app/endpoints/test_info.py
Unit test for /info endpoint handler
> Unit test for /info endpoint handler

- hooks/pre-commit
> Git pre-commit hook

- src/lightspeed_stack.py
- src/models/config.py
- tests/unit/models/test_config.py
Refactored configuration dump into model
> Refactored configuration dump into model

- docs/openapi.json
> Openapi.json

- tests/e2e/__init__.py
- tests/e2e/test_api.py
> Stub for end to end tests

- docs/openapi.json
Regenerated OpenAPI specification
> Regenerated OpenAPI specification

- Makefile
- README.md
- scripts/generate_openapi_schema.py
LCORE-215: Script to generate OpenAPI schema
- Related Issue #LCORE-215
> LCORE-215: Script to generate OpenAPI schema

- tests/unit/test_configuration.py
[minor] User data collection in unit tests
> [minor] User data collection in unit tests

- tests/integration/test_configuration.py
Enhanced integration tests for configuration
> Enhanced integration tests for configuration

- docs/installation_linux.md
- docs/installation_macos.md
LCORE-236: Fixed installation instructions
- Related Issue #LCORE-236
> LCORE-236: Fixed installation instructions

- tests/unit/runners/test_uvicorn_runner.py
LCORE-199: more unit tests for Uvicorn runner
- Related Issue #LCORE-199
> LCORE-199: more unit tests for Uvicorn runner

- tests/unit/test_lightspeed_stack.py
Simple unit test for argparser
> Simple unit test for argparser

- tests/e2e/features/environment.py
- tests/e2e/features/steps/common.py
- tests/e2e/features/steps/common_http.py
- tests/e2e/utils/utils.py
LCORE-232: Stub for end to end tests
- Related Issue #LCORE-232
> LCORE-232: Stub for end to end tests

- Makefile
- tests/e2e/features/smoketests.feature
- tests/e2e/features/steps/common_http.py
- tests/e2e/utils/utils.py
LCORE-232: End to end tests: smoketests
- Related Issue #LCORE-232
> LCORE-232: End to end tests: smoketests

- pdm.lock
- pyproject.toml
LCORE-232: Behave as devel dependency
- Related Issue #LCORE-232
> LCORE-232: Behave as devel dependency

- pyproject.toml
LCORE-218: version stored on one place
- Related Issue #LCORE-218
> LCORE-218: version stored on one place

- tests/configuration/lightspeed-stack.yaml
- tests/integration/test_configuration.py
- tests/unit/models/test_config.py
> Updated config tests

- pdm.lock
> Bump dependencies

- src/constants.py
- src/lightspeed_stack.py
- src/version.py
> Updated commends in sources

- tests/unit/models/test_config.py
- tests/unit/models/test_requests.py
- tests/unit/runners/test_uvicorn_runner.py
LCORE-303: improved unit tests
- Related Issue #LCORE-303
> LCORE-303: improved unit tests

- src/utils/common.py
- tests/unit/utils/test_common.py
TBD - maybe I don't understand how it should work.
- Closes #
> Skip MCP servers registration if there are no servers

- tests/e2e/features/steps/__init__.py
- tests/e2e/features/steps/llm_query_response.py
- tests/e2e/test_list.txt
LCORE-232: LLM query response end to end tests implementation
- Related Issue #LCORE-232
> LCORE-232: LLM query response end to end tests implementation

- README.md
- examples/run.yaml
LCORE-304: CLI arguments in docs
- Related Issue #LCORE-304
> LCORE-304: CLI arguments in docs

- examples/run.yaml
LCORE-201: Minimal Llama Stack configuration
- Related Issue #LCORE-201
> LCORE-201: Minimal Llama Stack configuration

- Makefile
LCORE-304: Makefile targets
- Related Issue #LCORE-304
> LCORE-304: Makefile targets

- src/app/endpoints/config.py
LCORE-217: proper description for config endpoint
- Related Issue #LCORE-217
> LCORE-217: proper description for config endpoint

- README.md
Add endpoints section into README.md
- Closes #
> LCORE-285: Add endpoints section into README.md

- README.md
LCORE-304: Service configuration
- Related Issue #LCORE-304
> LCORE-304: Service configuration

- src/utils/endpoints.py
LCORE-217: utilities for endpoints handlers
- Related Issue #LCORE-217
> LCORE-217: utilities for endpoints handlers

- docs/e2e_scenarios.md
- tests/e2e/gen_scenario_list.py
LCORE 317: tooling to generate list of scenarios
- Related Issue #LCORE-317
> LCORE 317: tooling to generate list of scenarios

- .github/workflows/build_and_push_dev.yaml
LCORE-326: Add restore dev tagging for image building
> LCORE-326: Add restore dev tagging for image building

- uv.lock
LCORE-316: bump-up dependencies #1
- Related Issue #LCORE-316
> LCORE-316: bump-up dependencies #1

- docs/installation_macos.md
- Related Issue #251 
- Closes #
> LCORE-304: Update to macOs docs

- uv.lock
LCORE-316: update packages
- Related Issue #LCORE-316
> LCORE-316: update packages

- docs/openapi.json
- docs/openapi.md
LCORE-248: update OpenAPI
- Related Issue #LCORE-248
> LCORE-248: update OpenAPI

- uv.lock
LCORE-380: upgrade packages in lockfile
- Related Issue #LCORE-380
> LCORE-380: upgrade packages in lockfile

- uv.lock
LCORE-336: update dependencies
- Related Issue #LCORE-336
> LCORE-336: update dependencies

- uv.lock
LCORE-535: Update dependencies
- Related Issue #LCORE-535
> LCORE-535: Update dependencies

- behave.ini
- pyproject.toml
LCORE-166: Behave config in Python project file
It will keep the root dir for the project cleaner
- Related Issue #LCORE-166
> LCORE-166: Behave config in Python project file

- docs/config.svg
> Configuration as SVG drawing

- uv.lock
LCORE-594: Bump-up dependencies
- Related Issue #LCORE-594
> LCORE-594: Bump-up dependencies

- uv.lock
LCORE-684: update dependencies
- Related Issue #LCORE-684
> LCORE-684: update dependencies

- uv.lock
LCORE-684: Bump-up dependencies
- Related Issue #LCORE-684
> LCORE-684: Bump-up dependencies

- uv.lock
LCORE-725: update deps
- Related Issue #LCORE-725
> LCORE-725: update deps

- uv.lock
LCORE-725: update dependencies
- Related Issue #LCORE-725
> LCORE-725: update dependencies
