lightspeed-core/lightspeed-stack

pyproject.toml
src/app/__init__.py
src/app/endpoints/info.py
src/app/main.py
src/app/routers.py
src/lightspeed-stack.py
src/runners/uvicorn.py
src/version.py

REST API service stub

---

src/app/endpoints/info.py
src/models/config.py
src/models/responses.py

Use models for REST API responses

Use models for REST API responses

---

src/app/endpoints/info.py
src/app/endpoints/models.py
src/app/endpoints/query.py
src/app/endpoints/root.py
src/app/main.py
src/app/routers.py
src/models/config.py
src/models/responses.py

Updated REST API endpoints

---

Makefile

New Makefile targets

---

lightspeed-stack.yaml
src/models/config.py

Llama-stack API key in configuration

Llama-stack API key in configuration

---

src/app/endpoints/query.py

Use llama-stack to retrieve LLM output

Use llama-stack to retrieve LLM output

---

lightspeed-stack.yaml
src/app/endpoints/query.py
src/models/config.py

Llama stack as library client

---

lightspeed-stack.yaml
src/app/endpoints/query.py
src/app/endpoints/root.py
src/models/config.py

Optional chat completion mode

---

src/app/endpoints/query.py
src/models/config.py

Support providing the path to a `llama-stack` configuration file when using it "as a library".
- Closes #
Try a configuration file:
```
name: foo bar baz
llama_stack:
use_as_library_client: true
library_client_config_path: /home/manstis/.llama/distributions/ollama/ollama-run.yaml
url: http://localhost:8321
api_key: xyzzy
chat_completion_mode: true
```

Support providing a 'stack' configuration for 'as a library' usage

---

lightspeed-stack.yaml
src/app/endpoints/query.py
src/models/config.py

I added support for invoking `input-shields` when defined.
I also remove the 'chat_completion_mode`... what purpose did it serve; other than bypassing use of an `agent`?
- Closes #

Add support for invoking input-shields. Remove 'chat' mode.

---

Makefile
pyproject.toml
tests/unit/test_configuration.py
tests/unit/test_log.py

Stub for unit tests

---

src/app/endpoints/models.py
src/app/endpoints/query.py
src/client.py
tests/unit/test_client.py

Refactoring getting llama stack client. Added unit tests.

Refactoring getting llama stack client

---

pyproject.toml
tests/configuration/lightspeed-stack.yaml
tests/unit/test_configuration.py
tests/unit/test_log.py

PYTHONPATH for unit tests

---

tests/unit/app/__init__.py
tests/unit/app/test_routers.py

Unit test for app.router

---

src/client.py
tests/unit/test_client.py

[Minor] check if library path is specified

[Minor] check if library path is specified

---

tests/unit/models/__init__.py
tests/unit/models/test_config.py

Unit tests for models config

---

pdm.lock
pyproject.toml

Bump-up `llama-stack` to 0.2.7

Bump-up llama-stack to 0.2.7

---

.gitignore
pdm.lock
pyproject.toml
src/app/endpoints/query.py
src/constants.py
src/models/requests.py
src/models/responses.py
tests/unit/app/endpoints/test_query.py
tests/unit/models/test_requests.py
tests/unit/models/test_responses.py

This patch add some compatibily with the /query endpoint from OLS-service.
For the request itself, everything should be identical now with the exception of the "media_type" field. The "media_type" field has not been included since the current implmentantion does not yet support streaming responses.
For the response to a query, there are a lot of fields missing. These also should be added as we start adding more features to Lightspeed Core. At the moment, only the basic response is returned.
TODOs were left in the code pointing to those gaps.
- [ x] Refactor
- [ x] Unit tests improvement
- Closes #
- [ x] I have performed a self-review of my code.
- The /query endpoint signature is now the same as the old ols-service project, you can curl it as before
- make test-unit, to …

Address /query endpoint compatibility

---

tests/unit/app/endpoints/test_query.py

LCORE-164: more unit tests for query endpoint
- Related Issue #LCORE-164

LCORE-164: more unit tests for query endpoint

---

src/app/endpoints/query.py

Added missing type hint into `/query` endpoint handler

Added missing type hint into /query endpoint handler

---

.github/workflows/ruff.yaml
src/app/endpoints/config.py
src/app/endpoints/models.py
src/app/main.py
tests/unit/app/endpoints/test_config.py
tests/unit/models/test_config.py
tests/unit/runners/test_uvicorn_runner.py

LCORE-161: GitHub action to run Ruff check
- Related Issue #LCORE-161

LCORE-161: GitHub action to run Ruff check

---

.github/workflows/pyright.yaml
README.md
pdm.lock
pyproject.toml
src/app/endpoints/query.py
src/app/main.py

Pyright setup on CI
- Related Issue #LCORE-161

LCORE-161: Pyright setup on CI

---

.github/workflows/black.yaml
.github/workflows/mypy.yaml
.github/workflows/pydocstyle.yaml
.github/workflows/pylint.yaml
.github/workflows/pyright.yaml
.github/workflows/ruff.yaml
Makefile
pdm.lock
pyproject.toml
src/app/endpoints/query.py

This patch refactors some of the GH workflow checks that we are running in the gate to make it eaier to run locally. That way we can verify the code prior to pushing it as a PR.
$ pdm verify
- Closes #
- pdm verify

Simplify running checks locally

---

CONTRIBUTING.md

Updated contributing guide: installation

Updated contributing guide: installation

---

tests/unit/models/test_config.py

Unit tests for feedback configuration

Unit tests for feedback configuration

---

pdm.lock
pyproject.toml
tests/configuration/minimal-stack.yaml
tests/unit/test_client.py

Added fix for LCORE-173. The fix includes adding a minimal llama-stack configuration file so that inference models don't need to be served during unit testing.
- Closes LCORE-173

LCORE-173: Fixed Unit Tests

---

CONTRIBUTING.md

LCORE-200: updated contributing guide
- Related Issue #LCORE-200

LCORE-200: updated contributing guide

---

CONTRIBUTING.md

Info about pre-commit
- Related Issue #LCORE-200

LCORE-200: Info about pre-commit

---

CONTRIBUTING.md

Info about linters
- Related Issue #LCORE-200

LCORE-200: Info about linters

---

.github/workflows/build.yaml
Containerfile

Add Containerfile for building container images. Add Github Actions for building container image with podman.

LCORE-168: Add image building - Containerfile and GH Actions

---

CONTRIBUTING.md

Info about code style
- Related Issue #LCORE-200

LCORE-200: Info about code style

---

pdm.lock

Bump-up packages in lockfile
- Related Issue #LCORE-228

LCORE-228: Bump-up packages in lockfile

---

.github/workflows/build.yaml

LCORE-168: GH actions: Check image building only on PRs. Image for distribution is built by quay.io on push to main branch.
- Related Issue #LCORE-168

LCORE-168: GH actions: Check image building only on PRs

---

lightspeed-stack.yaml
src/app/endpoints/feedback.py
src/app/endpoints/query.py
src/models/config.py
src/utils/common.py
tests/unit/app/endpoints/test_feedback.py
tests/unit/app/endpoints/test_query.py
tests/unit/models/test_config.py
tests/unit/utils/test_common.py

This patch adds support for storing transcripts in lightspeed-core. By default, transcripts are disabled.
The transcripts maintain the same format as they were implemented in road-core so the user data collector and existing pipeline should work seamlessly as before.
- Related Issue #LCORE-214
- Closes #
- Run unit-tests

Add support for storing transcripts

---

README.md

README - add instructions for running container image

LCORE-168: README - add instructions for running container image

---

src/app/main.py

- Remove asynccontextmanager lifespan implementation
- Use @app.on_event('startup') decorator instead
- Resolves RuntimeError: asyncio.run() cannot be called from a running event loop
- Maintains same startup functionality with compatible async context
- Closes #

fix: Replace lifespan context manager with startup event handler

---

src/app/main.py
src/utils/common.py
tests/unit/utils/test_common.py

Add async/await support for LlamaStackAsLibraryClient to prevent
"Cannot run event loop while another loop is running" RuntimeError.
Changes:
- Introduce register_mcp_servers_async() for async MCP server registration
- Refactor MCP registration logic into separate sync/async helper functions
- Use async client methods (client.async_client) for library clients
to avoid "Cannot run event loop while another loop is running" errors
- Add async tests for library client configuration
The LlamaStackAsLibraryClient requires async initialization, but the previous
sync implementation caused event loop conflicts. This change provides dual
support for both service clients (sync) and library clients (async).
Fixes RuntimeError when configuration.llama_stack.use_as_library_client = …

fix: resolve asyncio event loop conflicts in MCP server registration

---

pdm.lock

LCORE-237: Bump-up Uvicorn to 0.35.0
- Related Issue #LCORE-237

LCORE-237: Bump-up Uvicorn to 0.35.0

---

src/app/endpoints/query.py
src/app/endpoints/streaming_query.py
src/app/routers.py
src/client.py
tests/unit/app/endpoints/test_query.py
tests/unit/app/endpoints/test_streaming_query.py
tests/unit/app/test_routers.py
tests/unit/test_client.py

Added streaming_query endpoint as well as unit tests. The streaming_query endpoint is closely based off of the query endpoint. The unit tests for streaming_query were generated using vibe coding.
- Related Issue LCORE-177
- Closes LCORE-177

LCORE-177: Implemented streaming_query endpoint

---

.github/workflows/build_and_push_release.yaml

LCORE-311: GH actions release image building from tag

LCORE-311: GH actions release image building from tag

---

.github/workflows/build_and_push_dev.yaml

LCORE-311: build dev image from main with tag dev-latest

LCORE-311: build dev image from main with tag dev-latest

---

Makefile

- Add src parameter to pydocstyle to target correct directory
- Resolves docstyle verification issues during build process
- Closes #

Specify src directory for pydocstyle command in Makefile

---

README.md

LCORE-311: Update readme with image tag info

LCORE-311: Update readme with image tag info

---

docs/openapi.json
src/app/endpoints/models.py
tests/unit/app/endpoints/test_models.py

LCORE-217: Additional checks in /models endpoint
- Related Issue #LCORE-217

LCORE-217: Additional checks in /models endpoint

---

src/app/endpoints/streaming_query.py
tests/unit/app/endpoints/test_streaming_query.py

LCORE-217: Updated streaming query endpoint
- Related Issue #LCORE-217

LCORE-217: Updated streaming query endpoint

---

tests/e2e/features/steps/common.py

LCORE-303: silent improper Pyright warning in e2e's common.py
- Related Issue #LCORE-303

LCORE-303: silent improper Pyright warning in e2e's common.py

---

src/app/endpoints/streaming_query.py
tests/unit/app/endpoints/test_streaming_query.py

Referenced documents support on /streaming_query
The code assumes that the vector DB contains `docs_url` and `title` in metadata. They are found in the vector DB built for road-core/service.
- Related Issue # n/a
- Closes # n/a

Referenced documents support on /streaming_query

---

src/utils/checks.py
tests/unit/utils/test_checks.py

LCORE-293: config file utils
- Related Issue #LCORE-293

LCORE-293: config file utils

---

src/configuration.py
src/models/config.py
tests/unit/__init__.py
tests/unit/app/endpoints/test_config.py
tests/unit/app/endpoints/test_info.py
tests/unit/app/endpoints/test_models.py
tests/unit/app/endpoints/test_query.py
tests/unit/models/test_config.py
tests/unit/test_configuration.py
tests/unit/utils/test_common.py

LCORE-293: support for customization options
- Related Issue #LCORE-293

LCORE-293: support for customization options

---

src/app/endpoints/query.py
src/app/endpoints/streaming_query.py
src/utils/endpoints.py

LCORE-293: system prompt retrieval refactoring
- Related Issue #LCORE-293

LCORE-293: system prompt retrieval refactoring

---

README.md
src/utils/endpoints.py
tests/unit/utils/test_endpoints.py

LCORE-293: use customized system prompt if provided
- Related Issue #LCORE-293

LCORE-293: use customized system prompt if provided

---

Makefile
scripts/gen_doc.py
src/app/README.md
src/app/endpoints/README.md
src/auth/README.md
src/metrics/README.md
src/models/README.md
src/models/database/README.md
src/runners/README.md
src/utils/README.md

LCORE-581: generated documentation for all modules
- Related Issue #LCORE-581

LCORE-581: generated documentation for all modules

---

uv.lock

LCORE-684: Bump-up FastAPI to 0.118.0
- Related Issue #LCORE-684

LCORE-684: Bump-up FastAPI to 0.118.0
